FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_LIBJSON json)
SET(LIBJSON_DEFINITIONS ${PC_LIBJSON_CFLAGS_OTHER})

FIND_PATH(LIBJSON_INCLUDE_DIR NAMES json/json.h
    HINTS
   ${PC_LIBJSON_INCLUDEDIR}
   ${PC_LIBJSON_INCLUDE_DIRS}
  )

FIND_LIBRARY(LIBJSON_LIBRARY NAMES json libjson
    HINTS
   ${PC_LIBJSON_LIBDIR}
   ${PC_LIBJSON_LIBRARY_DIRS}
  )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibJson
                                  REQUIRED_VARS LIBJSON_LIBRARY LIBJSON_INCLUDE_DIR
                                  VERSION_VAR LIBJSON_VERSION_STRING)

MARK_AS_ADVANCED(LIBJSON_INCLUDE_DIR
                 LIBJSON_LIBRARY)
